language: php
php:
    - 5.5
    - 5.6
    - 7.0

before_script:
    - composer global require fabpot/php-cs-fixer
    - composer install --dev

script:
     - vendor/bin/phpunit
     - php php-cs-fixer --diff --dry-run -v fix .
