language: php

php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer global require friendsofphp/php-cs-fixer
    - composer global require sebastian/phpcpd
    - composer install --dev

script:
     - vendor/bin/phpunit
     - $HOME/.composer/vendor/bin/php-cs-fixer --diff --dry-run -v fix ./src
     - $HOME/.composer/vendor/bin/phpcpd ./src
