language: php

php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer global require fabpot/php-cs-fixer
    - composer install --dev

script:
     - vendor/bin/phpunit
     - $HOME/.config/composer/vendor/bin/php-cs-fixer --diff --dry-run -v fix .
